name = "PracticalStatistics"
uuid = "3208a211-90bf-4599-a200-bcf2e209b4c5"
authors = ["Gil Junqueira"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1.7.2"

[targets]
test = ["Test"]
